### ISSUE TITLE
Licence is copy-pasted from statehack

### ISSUE THREAD

**Issue by frankshearar** [lshift-de/contextual#2]
For example "**statehack** is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

Probably wants replacing with "contextual" :)

**Comment by akahl-owl** [comment]
Thanks @frankshearar!
